export interface BlogPost {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  excerpt: string;
  category: string;
  publishDate: string;
  modifiedDate: string;
  readTime: string;
  keywords: string[];
}

export const blogPosts: BlogPost[] = [
  {
    slug: "how-much-does-night-out-mayfair-cost",
    title: "How Much Does a Night Out in Mayfair Really Cost?",
    metaTitle: "How Much Does a Night Out in Mayfair Cost? 2025 Price Guide",
    metaDescription: "A transparent breakdown of what a luxury night out in Mayfair actually costs — from table minimums and bottle prices to dinner, taxis, and everything in between.",
    excerpt: "Everyone asks the question but nobody gives a straight answer. Here's exactly what you'll spend on a premium Mayfair night — with no sugarcoating.",
    category: "Planning",
    publishDate: "2026-01-20",
    modifiedDate: "2026-03-25",
    readTime: "8 min read",
    keywords: ["Mayfair night out cost", "how much bottle service London", "London club prices", "Mayfair club minimum spend"],
  },
  {
    slug: "bottle-service-london-explained",
    title: "Bottle Service in London Explained: What You Actually Get",
    metaTitle: "Bottle Service in London Explained | What It Costs & How It Works",
    metaDescription: "Everything you need to know about bottle service in London's luxury clubs — what's included, what it costs, how to book, and whether it's actually worth the money.",
    excerpt: "Bottle service is the currency of London's luxury nightlife — but most people don't fully understand what they're paying for. Let us break it down.",
    category: "Planning",
    publishDate: "2026-02-10",
    modifiedDate: "2026-03-25",
    readTime: "9 min read",
    keywords: ["bottle service London", "London club bottle service", "VIP bottle service explained", "table service London clubs"],
  },
  {
    slug: "new-years-eve-london-luxury-guide",
    title: "New Year's Eve in London: The Ultimate Luxury NYE Guide",
    metaTitle: "New Year's Eve London 2025 | Luxury NYE Club & Party Guide",
    metaDescription: "Plan the ultimate luxury New Year's Eve in London. The best NYE club events, VIP packages, dinner options, and insider tips for ringing in the new year in style.",
    excerpt: "NYE in London is a minefield of overpriced disappointments — unless you know where to go. Here's how to do it properly.",
    category: "Events",
    publishDate: "2026-01-05",
    modifiedDate: "2026-03-25",
    readTime: "10 min read",
    keywords: ["New Year's Eve London clubs", "luxury NYE London", "best NYE parties London", "New Year's Eve Mayfair"],
  },
  {
    slug: "birthday-night-out-london-planning-guide",
    title: "Planning a Birthday Night Out in London: The Complete Guide",
    metaTitle: "Birthday Night Out London | How to Plan the Perfect Celebration",
    metaDescription: "How to plan an unforgettable birthday night out in London's best clubs. Venue selection, group booking tips, birthday packages, and insider advice for every budget.",
    excerpt: "Your birthday night out in London deserves better than a last-minute scramble. Here's how to plan one that people actually talk about afterwards.",
    category: "Planning",
    publishDate: "2026-02-15",
    modifiedDate: "2026-03-25",
    readTime: "9 min read",
    keywords: ["birthday night out London", "birthday clubs London", "birthday party London nightclub", "birthday celebration London"],
  },
  {
    slug: "best-clubs-london-large-groups",
    title: "The Best London Clubs for Large Groups and Parties",
    metaTitle: "Best London Clubs for Groups | Large Party Venue Guide 2025",
    metaDescription: "Where to take a large group in London's nightlife scene. The best clubs for group bookings, stag and hen parties, corporate groups, and celebrations of 10+.",
    excerpt: "Taking a big group to a London club is a logistical challenge most people underestimate. Here's how to get everyone in, seated, and having the time of their lives.",
    category: "Planning",
    publishDate: "2026-02-20",
    modifiedDate: "2026-03-25",
    readTime: "8 min read",
    keywords: ["London clubs large groups", "group night out London", "best clubs for groups London", "party venues London nightclub"],
  },
  {
    slug: "mayfair-vs-shoreditch-nightlife-compared",
    title: "Mayfair vs Shoreditch: Two Sides of London's Nightlife",
    metaTitle: "Mayfair vs Shoreditch Nightlife | Which London Scene Is Right for You?",
    metaDescription: "A candid comparison of London's two biggest nightlife districts. How Mayfair's luxury clubs and Shoreditch's underground scene offer completely different nights out.",
    excerpt: "Two postcodes, two entirely different philosophies of what a night out should be. Here's how they compare — and which one suits you.",
    category: "Guide",
    publishDate: "2026-03-01",
    modifiedDate: "2026-03-25",
    readTime: "8 min read",
    keywords: ["Mayfair vs Shoreditch", "London nightlife areas", "best area for nightlife London", "Mayfair clubs vs Shoreditch bars"],
  },
  {
    slug: "saturday-night-mayfair-guide",
    title: "Saturday Night in Mayfair: A Local's Guide to the Perfect Evening",
    metaTitle: "Saturday Night in Mayfair | Insider's Guide to the Perfect Evening",
    metaDescription: "How to plan the perfect Saturday night in Mayfair — from pre-dinner cocktails to the best clubs, with a local's timing, venue picks, and insider knowledge.",
    excerpt: "Saturday in Mayfair follows a rhythm that locals understand instinctively. Here's the insider playbook for doing it right.",
    category: "Guide",
    publishDate: "2026-03-05",
    modifiedDate: "2026-03-25",
    readTime: "8 min read",
    keywords: ["Saturday night Mayfair", "Saturday night out London", "Mayfair Saturday clubs", "weekend nightlife Mayfair London"],
  },
  {
    slug: "london-late-night-venues-open-past-3am",
    title: "London After Dark: The Best Venues Open Past 3AM",
    metaTitle: "London Clubs Open Late | Best Venues Past 3AM Guide 2025",
    metaDescription: "Where to go when London's clubs close. The best late-night venues, after-parties, and spots open past 3AM for those who aren't ready for the night to end.",
    excerpt: "When most of Mayfair closes its doors at 3AM, the night doesn't have to end. Here's where London's real after-hours scene lives.",
    category: "Guide",
    publishDate: "2026-03-10",
    modifiedDate: "2026-03-25",
    readTime: "7 min read",
    keywords: ["London clubs open late", "late night London clubs", "after hours London", "clubs open past 3am London"],
  },
  {
    slug: "london-nightlife-2025-whats-new",
    title: "London Nightlife in 2025: What's New and What's Changed",
    metaTitle: "London Nightlife 2025 | New Clubs, Trends & What's Changed",
    metaDescription: "The state of London's luxury nightlife in 2025. New openings, closures, shifting trends, and what the scene looks like right now for anyone planning a night out.",
    excerpt: "London's club scene never stands still. Here's what's shifted, what's opened, and what you need to know if you haven't been out in a while.",
    category: "Trends",
    publishDate: "2026-03-15",
    modifiedDate: "2026-03-25",
    readTime: "8 min read",
    keywords: ["London nightlife 2025", "new clubs London 2025", "London club scene 2025", "best clubs London 2025"],
  },
  {
    slug: "funky-buddha-london-review",
    title: "Funky Buddha London: Why This Mayfair Icon Still Delivers",
    metaTitle: "Funky Buddha London Review | Mayfair's Iconic Nightclub",
    metaDescription: "An insider's look at Funky Buddha London — the Mayfair nightclub that's been a celebrity favourite for over a decade. What it's like, who goes, and why it endures.",
    excerpt: "The club that helped define Mayfair's nightlife reputation — and why it's still worth your time after all these years.",
    category: "Venue",
    publishDate: "2026-03-18",
    modifiedDate: "2026-03-25",
    readTime: "7 min read",
    keywords: ["Funky Buddha London", "Funky Buddha Mayfair", "Funky Buddha review", "Funky Buddha nightclub"],
  },
  {
    slug: "the-box-london-what-to-expect",
    title: "The Box London: What to Expect at London's Most Provocative Club",
    metaTitle: "The Box London | What to Expect at Soho's Most Daring Nightclub",
    metaDescription: "An honest guide to The Box London — Soho's most provocative nightclub. What the shows are like, the door policy, how to get in, and who should (and shouldn't) go.",
    excerpt: "An honest guide to the venue that makes every other nightclub in London look tame.",
    category: "Venue",
    publishDate: "2026-03-18",
    modifiedDate: "2026-03-25",
    readTime: "7 min read",
    keywords: ["The Box London", "The Box Soho", "The Box nightclub London", "what is The Box London like"],
  },
  {
    slug: "best-clubs-mayfair-complete-ranking",
    title: "Every Mayfair Club Ranked: The Definitive Guide for 2025",
    metaTitle: "Best Clubs in Mayfair Ranked | Definitive 2025 Guide",
    metaDescription: "An honest ranking of every luxury nightclub in Mayfair for 2025. From established icons to the newest openings — the definitive insider's guide.",
    excerpt: "An honest ranking of every luxury nightclub in Mayfair — from the established icons to the newest openings.",
    category: "Guide",
    publishDate: "2026-03-20",
    modifiedDate: "2026-03-25",
    readTime: "10 min read",
    keywords: ["best clubs Mayfair", "Mayfair clubs ranked", "top Mayfair nightclubs", "best nightclub Mayfair 2025"],
  },
  {
    slug: "reign-london-showclub-experience",
    title: "Inside Reign London: Is the Showclub Experience Worth It?",
    metaTitle: "Reign London Review | Inside Piccadilly's Showclub Experience",
    metaDescription: "What it's really like inside Reign London — Piccadilly's most theatrical night out. The shows, the spectacle, and who should book. Formerly The London Reign.",
    excerpt: "What it's really like inside Piccadilly's most theatrical night out — and who should book.",
    category: "Venue",
    publishDate: "2026-03-20",
    modifiedDate: "2026-03-25",
    readTime: "7 min read",
    keywords: ["Reign London", "Reign London review", "Reign nightclub London", "Reign London showclub"],
  },
  {
    slug: "scotch-of-st-james-history-legacy",
    title: "Scotch of St James: The History and Legacy of London's Most Storied Club",
    metaTitle: "Scotch of St James History | London's Most Legendary Club",
    metaDescription: "From Jimi Hendrix in the 1960s to today — the incredible history of Scotch of St James, Mayfair's most storied nightclub and why it still matters.",
    excerpt: "From Jimi Hendrix to today — how one Mayfair basement became nightlife royalty.",
    category: "Venue",
    publishDate: "2026-03-22",
    modifiedDate: "2026-03-25",
    readTime: "7 min read",
    keywords: ["Scotch of St James", "Scotch of St James history", "Scotch of St James London", "Scotch Mayfair"],
  },
  {
    slug: "dear-darling-maddox-cocktail-clubs-mayfair",
    title: "Dear Darling vs Maddox: Mayfair's Best Cocktail-to-Club Experiences",
    metaTitle: "Dear Darling vs Maddox Club | Mayfair Cocktail-to-Club Guide",
    metaDescription: "Two Mayfair venues that blend cocktails with late-night energy. Dear Darling vs Maddox — which suits your style and how each handles the transition from elegant to electric.",
    excerpt: "Two venues that prove you don't have to choose between sophistication and a great party.",
    category: "Venue",
    publishDate: "2026-03-22",
    modifiedDate: "2026-03-25",
    readTime: "7 min read",
    keywords: ["Dear Darling Mayfair", "Maddox club London", "cocktail clubs Mayfair", "best cocktail bars Mayfair nightlife"],
  },
  {
    slug: "tape-london-inside-mayfairs-most-exclusive-club",
    title: "Inside Tape London: What Makes Mayfair's Most Exclusive Club Different",
    metaTitle: "Inside Tape London | Mayfair's Most Exclusive Nightclub",
    metaDescription: "An insider's look at Tape London — the Hanover Square members' club where celebrities and music industry insiders go for genuine privacy and exceptional sound.",
    excerpt: "The Hanover Square members' club where privacy, sound quality, and genuine exclusivity converge.",
    category: "Venue",
    publishDate: "2026-03-23",
    modifiedDate: "2026-03-25",
    readTime: "7 min read",
    keywords: ["Tape London", "Tape London review", "most exclusive club London", "Tape London Mayfair"],
  },
  {
    slug: "cirque-le-soir-circus-nightclub-london",
    title: "Cirque Le Soir: Inside London's Most Theatrical Nightclub",
    metaTitle: "Cirque Le Soir London | Inside the Circus Nightclub",
    metaDescription: "What it's really like inside Cirque Le Soir — the circus-themed Soho nightclub where fire breathers, contortionists, and celebrities share the dance floor.",
    excerpt: "Fire breathers, contortionists, and a crowd that includes half of Instagram — what to expect inside.",
    category: "Venue",
    publishDate: "2026-03-23",
    modifiedDate: "2026-03-25",
    readTime: "7 min read",
    keywords: ["Cirque Le Soir London", "Cirque Le Soir review", "circus nightclub London", "Cirque Le Soir experience"],
  },
  {
    slug: "tabu-london-japanese-underground-nightclub",
    title: "TABU London: Inside Mayfair's Japanese-Inspired Underground Club",
    metaTitle: "TABU London Review | Japanese Underground Nightclub Mayfair",
    metaDescription: "What makes TABU London different from every other Mayfair nightclub. The Japanese aesthetics, the underground atmosphere, and why this venue is the antidote to Mayfair sameness.",
    excerpt: "The venue that proves Mayfair can still surprise you — Japanese aesthetics meet underground energy.",
    category: "Venue",
    publishDate: "2026-03-23",
    modifiedDate: "2026-03-25",
    readTime: "7 min read",
    keywords: ["TABU London", "TABU nightclub Mayfair", "Japanese nightclub London", "underground club Mayfair"],
  },
  {
    slug: "cuckoo-club-mayfair-two-floors-one-night",
    title: "Cuckoo Club Mayfair: Two Floors, One Perfect Night",
    metaTitle: "Cuckoo Club London Review | Mayfair's Best Two-Floor Nightclub",
    metaDescription: "Why Cuckoo Club on Swallow Street is Mayfair's most reliable night out. Two floors, two genres, and a consistency that more famous venues struggle to match.",
    excerpt: "The Swallow Street venue that solves the genre debate — and delivers the most consistent nights in Mayfair.",
    category: "Venue",
    publishDate: "2026-03-24",
    modifiedDate: "2026-03-25",
    readTime: "7 min read",
    keywords: ["Cuckoo Club London", "Cuckoo Club Mayfair", "Cuckoo Club review", "Swallow Street nightclub"],
  },
  {
    slug: "beat-london-sound-system-fitzrovia",
    title: "BEAT London: The Sound System That Sets This Fitzrovia Club Apart",
    metaTitle: "BEAT London Review | Best Sound System in a London Nightclub",
    metaDescription: "Why BEAT London on Margaret Street has one of the best sound systems in the city. A club built for people who care about music first and everything else second.",
    excerpt: "The Margaret Street club that strips away the Mayfair pretence and puts the music first.",
    category: "Venue",
    publishDate: "2026-03-24",
    modifiedDate: "2026-03-25",
    readTime: "7 min read",
    keywords: ["BEAT London", "BEAT nightclub", "best sound system London club", "Margaret Street nightclub"],
  },
  {
    slug: "luna-selene-new-mayfair-clubs-2025",
    title: "Luna Club and Selene London: Mayfair's Newest Luxury Clubs Reviewed",
    metaTitle: "Luna Club & Selene London | New Mayfair Clubs 2025 Review",
    metaDescription: "An insider review of Luna Club London and Selene London — Mayfair's two newest luxury nightclubs. How they compare and whether the new arrivals can compete.",
    excerpt: "How Mayfair's freshest arrivals compare — and whether the new generation can compete with the established names.",
    category: "Venue",
    publishDate: "2026-03-24",
    modifiedDate: "2026-03-25",
    readTime: "8 min read",
    keywords: ["Luna Club London", "Selene London", "new Mayfair clubs", "new clubs London 2025"],
  },
  {
    slug: "best-thursday-night-clubs-london",
    title: "Best Thursday Night Clubs in London",
    metaTitle: "Best Thursday Night Clubs London | Where to Go on a Thursday",
    metaDescription: "The best London clubs open on Thursday night. Which venues are worth it, what the crowd is like, and why Thursday is Mayfair's best-kept secret.",
    excerpt: "Thursday is when London's luxury clubs feel most like insider secrets — smaller crowds, easier entry, and the industry crowd comes out to play.",
    category: "Guide",
    publishDate: "2026-03-25",
    modifiedDate: "2026-03-25",
    readTime: "7 min read",
    keywords: ["best Thursday night clubs London", "Thursday night out London", "London clubs Thursday", "Thursday clubbing London"],
  },
  {
    slug: "best-friday-night-clubs-london",
    title: "Best Friday Night Clubs in London",
    metaTitle: "Best Friday Night Clubs London | The Main Event Guide",
    metaDescription: "The best London clubs for Friday night. Where to go, what to expect, and how to make the most of the biggest night of the week in Mayfair and beyond.",
    excerpt: "Friday is the main event — and choosing the right venue makes the difference between a great night and a forgettable one.",
    category: "Guide",
    publishDate: "2026-03-25",
    modifiedDate: "2026-03-25",
    readTime: "7 min read",
    keywords: ["best Friday night clubs London", "Friday night out London", "London clubs Friday night", "best clubs Friday London"],
  },
  {
    slug: "london-nightlife-etiquette-unwritten-rules",
    title: "London Nightlife Etiquette: The Unwritten Rules",
    metaTitle: "London Nightlife Etiquette | The Unwritten Rules Nobody Tells You",
    metaDescription: "The unwritten rules of London's luxury nightlife scene. Phone etiquette, tipping protocol, VIP behaviour, and everything nobody tells you before your first night out.",
    excerpt: "Dress code gets you through the door. Etiquette determines whether you're invited back.",
    category: "Guide",
    publishDate: "2026-03-25",
    modifiedDate: "2026-03-25",
    readTime: "9 min read",
    keywords: ["London nightlife etiquette", "London club etiquette", "nightclub manners London", "unwritten rules London clubs"],
  },
  {
    slug: "best-cocktail-bars-mayfair-before-clubbing",
    title: "Best Cocktail Bars Near Mayfair Clubs for Pre-Drinks",
    metaTitle: "Best Pre-Club Cocktail Bars Mayfair | Where to Drink Before Clubbing",
    metaDescription: "The best cocktail bars near Mayfair's clubs for pre-drinks. Where to start your evening, what to order, and how to time the transition to the club perfectly.",
    excerpt: "The right pre-club bar sets the tone for the entire evening. Here are the ones that do it best.",
    category: "Guide",
    publishDate: "2026-03-25",
    modifiedDate: "2026-03-25",
    readTime: "7 min read",
    keywords: ["best cocktail bars Mayfair before clubbing", "pre-drinks Mayfair", "cocktail bars near Mayfair clubs", "pre-club bars Mayfair"],
  },
  {
    slug: "private-members-clubs-vs-nightclubs-london",
    title: "Private Members Clubs vs Public Nightclubs in London",
    metaTitle: "Members Clubs vs Nightclubs London | Which Is Right for You?",
    metaDescription: "Private members clubs or public nightclubs — which suits you? An honest comparison of atmosphere, cost, exclusivity, and what you actually get for your money in London.",
    excerpt: "Two very different approaches to exclusivity — and the answer to which is better depends entirely on what you're looking for.",
    category: "Guide",
    publishDate: "2026-03-25",
    modifiedDate: "2026-03-25",
    readTime: "8 min read",
    keywords: ["private members clubs vs nightclubs London", "London members clubs nightlife", "members club or nightclub London"],
  },
  {
    slug: "best-london-clubs-over-30s",
    title: "Best London Clubs for Over 30s",
    metaTitle: "Best London Clubs for Over 30s | Where the Grown-Up Crowd Goes",
    metaDescription: "The best London nightclubs for people in their 30s and 40s. Where the crowd is mature, the service is exceptional, and you won't feel out of place.",
    excerpt: "Mayfair's luxury scene was built for people who've outgrown sticky-floored student nights. Here's where the grown-up crowd goes.",
    category: "Guide",
    publishDate: "2026-03-25",
    modifiedDate: "2026-03-25",
    readTime: "7 min read",
    keywords: ["best London clubs over 30s", "London nightlife over 30", "clubs for older crowd London", "mature nightlife London"],
  },
  {
    slug: "soho-nightlife-guide",
    title: "Soho Nightlife Guide: The Box, Cirque Le Soir and Beyond",
    metaTitle: "Soho Nightlife Guide | The Box, Cirque Le Soir & Beyond",
    metaDescription: "The insider's guide to Soho nightlife. From The Box and Cirque Le Soir to late-night bars and the walk to Mayfair — everything you need for a night in Soho.",
    excerpt: "Soho's nightlife plays by different rules to Mayfair — grittier, more creative, and with a few genuine surprises.",
    category: "Guide",
    publishDate: "2026-03-25",
    modifiedDate: "2026-03-25",
    readTime: "7 min read",
    keywords: ["Soho nightlife guide", "best clubs Soho London", "Soho nightlife", "nightclubs Soho"],
  },
  {
    slug: "london-nightlife-mistakes-first-timers",
    title: "London Nightlife Mistakes First-Timers Make",
    metaTitle: "London Nightlife Mistakes | 12 Errors First-Timers Make",
    metaDescription: "The most common London nightlife mistakes and how to avoid them. From dress code disasters to timing errors — everything first-timers get wrong.",
    excerpt: "Every mistake on this list costs you either money, dignity, or both. Here's how to avoid all of them.",
    category: "Guide",
    publishDate: "2026-03-25",
    modifiedDate: "2026-03-25",
    readTime: "9 min read",
    keywords: ["London nightlife mistakes", "London clubbing mistakes", "first time London nightlife tips", "what not to do London clubs"],
  },
  {
    slug: "how-london-vip-clubs-work-behind-scenes",
    title: "How London's VIP Clubs Actually Work Behind the Scenes",
    metaTitle: "How London VIP Clubs Work | Behind the Scenes Guide",
    metaDescription: "How London's VIP clubs really operate — the promoter system, table allocation, celebrity management, and the economics of a Saturday night behind the velvet rope.",
    excerpt: "Pull back the curtain on how a Mayfair VIP club actually runs — from setup to sunrise.",
    category: "Guide",
    publishDate: "2026-03-25",
    modifiedDate: "2026-03-25",
    readTime: "9 min read",
    keywords: ["how London VIP clubs work", "behind the scenes London clubs", "London club promoter system", "how VIP clubs work"],
  },
  {
    slug: "london-fashion-week-nightlife-guide",
    title: "London Fashion Week Nightlife: Where the Industry Goes After Dark",
    metaTitle: "London Fashion Week Nightlife | Where the Industry Goes After Dark",
    metaDescription: "Where to go out during London Fashion Week. The afterparties, the clubs, the fashion crowd — an insider's guide to LFW nightlife in Mayfair and Soho.",
    excerpt: "When fashion week hits London, the nightlife scene transforms. Here's where the industry actually goes.",
    category: "Events",
    publishDate: "2026-03-25",
    modifiedDate: "2026-03-25",
    readTime: "7 min read",
    keywords: ["London Fashion Week nightlife", "LFW afterparties", "fashion week clubs London", "fashion week parties London"],
  },
];
