export interface BlogPost {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  excerpt: string;
  category: string;
  publishDate: string;
  modifiedDate: string;
  readTime: string;
  keywords: string[];
}

export const blogPosts: BlogPost[] = [
  {
    slug: "how-much-does-night-out-mayfair-cost",
    title: "How Much Does a Night Out in Mayfair Really Cost?",
    metaTitle: "How Much Does a Night Out in Mayfair Cost? 2025 Price Guide",
    metaDescription: "A transparent breakdown of what a luxury night out in Mayfair actually costs — from table minimums and bottle prices to dinner, taxis, and everything in between.",
    excerpt: "Everyone asks the question but nobody gives a straight answer. Here's exactly what you'll spend on a premium Mayfair night — with no sugarcoating.",
    category: "Planning",
    publishDate: "2025-01-20",
    modifiedDate: "2025-03-01",
    readTime: "8 min read",
    keywords: ["Mayfair night out cost", "how much bottle service London", "London club prices", "Mayfair club minimum spend"],
  },
  {
    slug: "best-clubs-london-hip-hop-rnb",
    title: "The Best Clubs in London for Hip-Hop and RnB",
    metaTitle: "Best Hip-Hop & RnB Clubs in London | 2025 Insider Guide",
    metaDescription: "An insider's ranking of the best hip-hop and RnB clubs in London — from Mayfair's elite VIP rooms to high-energy dancefloors that deliver every weekend.",
    excerpt: "London's hip-hop scene is concentrated in Mayfair, but not every club gets it right. Here's where the sound, the crowd, and the energy actually align.",
    category: "Music",
    publishDate: "2025-02-01",
    modifiedDate: "2025-03-01",
    readTime: "7 min read",
    keywords: ["hip hop clubs London", "RnB clubs London", "best hip hop nights London", "London clubs hip hop music"],
  },
  {
    slug: "bottle-service-london-explained",
    title: "Bottle Service in London Explained: What You Actually Get",
    metaTitle: "Bottle Service in London Explained | What It Costs & How It Works",
    metaDescription: "Everything you need to know about bottle service in London's luxury clubs — what's included, what it costs, how to book, and whether it's actually worth the money.",
    excerpt: "Bottle service is the currency of London's luxury nightlife — but most people don't fully understand what they're paying for. Let us break it down.",
    category: "Planning",
    publishDate: "2025-02-10",
    modifiedDate: "2025-03-01",
    readTime: "9 min read",
    keywords: ["bottle service London", "London club bottle service", "VIP bottle service explained", "table service London clubs"],
  },
  {
    slug: "new-years-eve-london-luxury-guide",
    title: "New Year's Eve in London: The Ultimate Luxury NYE Guide",
    metaTitle: "New Year's Eve London 2025 | Luxury NYE Club & Party Guide",
    metaDescription: "Plan the ultimate luxury New Year's Eve in London. The best NYE club events, VIP packages, dinner options, and insider tips for ringing in the new year in style.",
    excerpt: "NYE in London is a minefield of overpriced disappointments — unless you know where to go. Here's how to do it properly.",
    category: "Events",
    publishDate: "2025-01-05",
    modifiedDate: "2025-03-01",
    readTime: "10 min read",
    keywords: ["New Year's Eve London clubs", "luxury NYE London", "best NYE parties London", "New Year's Eve Mayfair"],
  },
  {
    slug: "birthday-night-out-london-planning-guide",
    title: "Planning a Birthday Night Out in London: The Complete Guide",
    metaTitle: "Birthday Night Out London | How to Plan the Perfect Celebration",
    metaDescription: "How to plan an unforgettable birthday night out in London's best clubs. Venue selection, group booking tips, birthday packages, and insider advice for every budget.",
    excerpt: "Your birthday night out in London deserves better than a last-minute scramble. Here's how to plan one that people actually talk about afterwards.",
    category: "Planning",
    publishDate: "2025-02-15",
    modifiedDate: "2025-03-01",
    readTime: "9 min read",
    keywords: ["birthday night out London", "birthday clubs London", "birthday party London nightclub", "birthday celebration London"],
  },
  {
    slug: "best-clubs-london-large-groups",
    title: "The Best London Clubs for Large Groups and Parties",
    metaTitle: "Best London Clubs for Groups | Large Party Venue Guide 2025",
    metaDescription: "Where to take a large group in London's nightlife scene. The best clubs for group bookings, stag and hen parties, corporate groups, and celebrations of 10+.",
    excerpt: "Taking a big group to a London club is a logistical challenge most people underestimate. Here's how to get everyone in, seated, and having the time of their lives.",
    category: "Planning",
    publishDate: "2025-02-20",
    modifiedDate: "2025-03-01",
    readTime: "8 min read",
    keywords: ["London clubs large groups", "group night out London", "best clubs for groups London", "party venues London nightclub"],
  },
  {
    slug: "mayfair-vs-shoreditch-nightlife-compared",
    title: "Mayfair vs Shoreditch: Two Sides of London's Nightlife",
    metaTitle: "Mayfair vs Shoreditch Nightlife | Which London Scene Is Right for You?",
    metaDescription: "A candid comparison of London's two biggest nightlife districts. How Mayfair's luxury clubs and Shoreditch's underground scene offer completely different nights out.",
    excerpt: "Two postcodes, two entirely different philosophies of what a night out should be. Here's how they compare — and which one suits you.",
    category: "Guide",
    publishDate: "2025-03-01",
    modifiedDate: "2025-03-15",
    readTime: "8 min read",
    keywords: ["Mayfair vs Shoreditch", "London nightlife areas", "best area for nightlife London", "Mayfair clubs vs Shoreditch bars"],
  },
  {
    slug: "saturday-night-mayfair-guide",
    title: "Saturday Night in Mayfair: A Local's Guide to the Perfect Evening",
    metaTitle: "Saturday Night in Mayfair | Insider's Guide to the Perfect Evening",
    metaDescription: "How to plan the perfect Saturday night in Mayfair — from pre-dinner cocktails to the best clubs, with a local's timing, venue picks, and insider knowledge.",
    excerpt: "Saturday in Mayfair follows a rhythm that locals understand instinctively. Here's the insider playbook for doing it right.",
    category: "Guide",
    publishDate: "2025-03-05",
    modifiedDate: "2025-03-15",
    readTime: "8 min read",
    keywords: ["Saturday night Mayfair", "Saturday night out London", "Mayfair Saturday clubs", "weekend nightlife Mayfair London"],
  },
  {
    slug: "london-late-night-venues-open-past-3am",
    title: "London After Dark: The Best Venues Open Past 3AM",
    metaTitle: "London Clubs Open Late | Best Venues Past 3AM Guide 2025",
    metaDescription: "Where to go when London's clubs close. The best late-night venues, after-parties, and spots open past 3AM for those who aren't ready for the night to end.",
    excerpt: "When most of Mayfair closes its doors at 3AM, the night doesn't have to end. Here's where London's real after-hours scene lives.",
    category: "Guide",
    publishDate: "2025-03-10",
    modifiedDate: "2025-03-15",
    readTime: "7 min read",
    keywords: ["London clubs open late", "late night London clubs", "after hours London", "clubs open past 3am London"],
  },
  {
    slug: "london-nightlife-2025-whats-new",
    title: "London Nightlife in 2025: What's New and What's Changed",
    metaTitle: "London Nightlife 2025 | New Clubs, Trends & What's Changed",
    metaDescription: "The state of London's luxury nightlife in 2025. New openings, closures, shifting trends, and what the scene looks like right now for anyone planning a night out.",
    excerpt: "London's club scene never stands still. Here's what's shifted, what's opened, and what you need to know if you haven't been out in a while.",
    category: "Trends",
    publishDate: "2025-03-15",
    modifiedDate: "2025-03-20",
    readTime: "8 min read",
    keywords: ["London nightlife 2025", "new clubs London 2025", "London club scene 2025", "best clubs London 2025"],
  },
];
