import type { Metadata } from "next";
import type { ComponentType } from "react";

// The site's original posts, one module per post (each was
// app/blog/<slug>/page.tsx and is unchanged). app/blog/[slug] renders them,
// unless a content-API post in the database supersedes the slug. New posts
// are published through the content API, not added here.
export type LegacyPostModule = { metadata: Metadata; default: ComponentType };

export const legacyPosts: Record<string, () => Promise<LegacyPostModule>> = {
  "anniversary-night-out-london-planning": () => import("./anniversary-night-out-london-planning"),
  "beat-london-sound-system-fitzrovia": () => import("./beat-london-sound-system-fitzrovia"),
  "best-clubs-london-large-groups": () => import("./best-clubs-london-large-groups"),
  "best-clubs-mayfair-complete-ranking": () => import("./best-clubs-mayfair-complete-ranking"),
  "best-cocktail-bars-mayfair-before-clubbing": () => import("./best-cocktail-bars-mayfair-before-clubbing"),
  "best-friday-night-clubs-london": () => import("./best-friday-night-clubs-london"),
  "best-london-clubs-over-30s": () => import("./best-london-clubs-over-30s"),
  "best-thursday-night-clubs-london": () => import("./best-thursday-night-clubs-london"),
  "birthday-night-out-london-planning-guide": () => import("./birthday-night-out-london-planning-guide"),
  "bottle-service-london-explained": () => import("./bottle-service-london-explained"),
  "british-grand-prix-london-nightlife": () => import("./british-grand-prix-london-nightlife"),
  "cirque-le-soir-circus-nightclub-london": () => import("./cirque-le-soir-circus-nightclub-london"),
  "cuckoo-club-mayfair-two-floors-one-night": () => import("./cuckoo-club-mayfair-two-floors-one-night"),
  "dear-darling-maddox-cocktail-clubs-mayfair": () => import("./dear-darling-maddox-cocktail-clubs-mayfair"),
  "fight-night-london-nightlife": () => import("./fight-night-london-nightlife"),
  "frieze-week-london-nightlife": () => import("./frieze-week-london-nightlife"),
  "funky-buddha-london-review": () => import("./funky-buddha-london-review"),
  "glorious-goodwood-london-season-finale": () => import("./glorious-goodwood-london-season-finale"),
  "henley-regatta-london-nightlife": () => import("./henley-regatta-london-nightlife"),
  "host-private-event-london-nightclub": () => import("./host-private-event-london-nightclub"),
  "how-london-vip-clubs-work-behind-scenes": () => import("./how-london-vip-clubs-work-behind-scenes"),
  "how-much-does-night-out-mayfair-cost": () => import("./how-much-does-night-out-mayfair-cost"),
  "london-clubs-going-cashless": () => import("./london-clubs-going-cashless"),
  "london-fashion-week-nightlife-guide": () => import("./london-fashion-week-nightlife-guide"),
  "london-film-premiere-after-parties": () => import("./london-film-premiere-after-parties"),
  "london-late-night-venues-open-past-3am": () => import("./london-late-night-venues-open-past-3am"),
  "london-nightlife-2025-whats-new": () => import("./london-nightlife-2025-whats-new"),
  "london-nightlife-etiquette-unwritten-rules": () => import("./london-nightlife-etiquette-unwritten-rules"),
  "london-nightlife-mistakes-first-timers": () => import("./london-nightlife-mistakes-first-timers"),
  "london-supercar-season-nightlife": () => import("./london-supercar-season-nightlife"),
  "london-to-mykonos-club-scene-summer": () => import("./london-to-mykonos-club-scene-summer"),
  "luna-selene-new-mayfair-clubs-2025": () => import("./luna-selene-new-mayfair-clubs-2025"),
  "luxury-night-transport-london": () => import("./luxury-night-transport-london"),
  "mayfair-vs-shoreditch-nightlife-compared": () => import("./mayfair-vs-shoreditch-nightlife-compared"),
  "new-years-eve-london-luxury-guide": () => import("./new-years-eve-london-luxury-guide"),
  "private-members-clubs-vs-nightclubs-london": () => import("./private-members-clubs-vs-nightclubs-london"),
  "private-views-london-art-world": () => import("./private-views-london-art-world"),
  "quiet-luxury-london-nightlife": () => import("./quiet-luxury-london-nightlife"),
  "reign-london-showclub-experience": () => import("./reign-london-showclub-experience"),
  "royal-ascot-week-nightlife-london": () => import("./royal-ascot-week-nightlife-london"),
  "saturday-night-mayfair-guide": () => import("./saturday-night-mayfair-guide"),
  "scotch-of-st-james-history-legacy": () => import("./scotch-of-st-james-history-legacy"),
  "soho-nightlife-guide": () => import("./soho-nightlife-guide"),
  "stag-night-mayfair-guide": () => import("./stag-night-mayfair-guide"),
  "tabu-london-japanese-underground-nightclub": () => import("./tabu-london-japanese-underground-nightclub"),
  "tape-london-inside-mayfairs-most-exclusive-club": () => import("./tape-london-inside-mayfairs-most-exclusive-club"),
  "the-box-london-what-to-expect": () => import("./the-box-london-what-to-expect"),
  "wimbledon-season-nightlife-london": () => import("./wimbledon-season-nightlife-london"),
};
